name: Build image ctsearch

on:
  workflow_dispatch:  # manually

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout repository
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    # Login Ghcr
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    # ReleaseTag
    - name: Set Version
      id: set-version
      run: |
        echo "version=ver$(date +'%Y-%m-%d')" >> $GITHUB_ENV

   # Build and push to ghcr
    - name: Build and push to ghcr
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/mkz9s4vy/ctsearch:${{ env.version }}
          ghcr.io/mkz9s4vy/ctsearch:latest