name: Sync and Build Hexo

on:
  workflow_dispatch:  # manually

jobs:
  uild:
    runs-on: ubuntu-latest

    # Checkout repository
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    # Docker Image
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login Ghcr
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    # ReleaseTag
    - name: Set Version
      id: set-version
      run: |
        echo "version=`date +'%y-%m-%d'`" >> $GITHUB_ENV

   # Build and push to ghcr
    - name: Build and push to ghcr
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/mkz9s4vy/ctsearch:${{ env.version }}
          ghcr.io/mkz9s4vy/ctsearch:latest